on:
  issues:
    types: [opened]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload
        run: echo "${{ toJson(github.event.issue.title) }}"
             
